apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushprox-client
spec:
  template:
    spec:
      containers:
      - name: pushprox-client
        args: ["--metrics-addr", ":8080", "--proxy-url", "http://pushprox-proxy-manuela-acm-aggregator.apps.ocp3.stormshift.coe.muc.redhat.com", "--fqdn=prometheus-operated.argocd.svc"]
